# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "843004e81a585f3b3de0c673b7461f38"
name = "Oirsoy Custom"
application_url = "https://sectors-zoloft-dear-met.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "oirsoy-custom.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,write_products"

[auth]
redirect_urls = [
  "https://sectors-zoloft-dear-met.trycloudflare.com/auth/callback",
  "https://sectors-zoloft-dear-met.trycloudflare.com/auth/shopify/callback",
  "https://sectors-zoloft-dear-met.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
